/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/


INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (1, N'For Those About To Rock We Salute You', 1)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (2, N'Balls to the Wall', 2)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (3, N'Restless and Wild', 2)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (4, N'Let There Be Rock', 1)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (5, N'Big Ones', 3)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (6, N'Jagged Little Pill', 4)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (7, N'Facelift', 5)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (8, N'Warner 25 Anos', 6)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (9, N'Plays Metallica By Four Cellos', 7)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (10, N'Audioslave', 8)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (11, N'Out Of Exile', 8)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (12, N'BackBeat Soundtrack', 9)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (13, N'The Best Of Billy Cobham', 10)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (14, N'Alcohol Fueled Brewtality Live! [Disc 1]', 11)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (15, N'Alcohol Fueled Brewtality Live! [Disc 2]', 11)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (16, N'Black Sabbath', 12)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (17, N'Black Sabbath Vol. 4 (Remaster)', 12)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (18, N'Body Count', 13)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (19, N'Chemical Wedding', 14)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (20, N'The Best Of Buddy Guy - The Millenium Collection', 15)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (21, N'Prenda Minha', 16)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (22, N'Sozinho Remix Ao Vivo', 16)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (23, N'Minha Historia', 17)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (24, N'Afrociberdelia', 18)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (25, N'Da Lama Ao Caos', 18)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (26, N'Acústico MTV [Live]', 19)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (27, N'Cidade Negra - Hits', 19)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (28, N'Na Pista', 20)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (29, N'Axé Bahia 2001', 21)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (30, N'BBC Sessions [Disc 1] [Live]', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (31, N'Bongo Fury', 23)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (32, N'Carnaval 2001', 21)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (33, N'Chill: Brazil (Disc 1)', 24)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (34, N'Chill: Brazil (Disc 2)', 6)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (35, N'Garage Inc. (Disc 1)', 50)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (36, N'Greatest Hits II', 51)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (37, N'Greatest Kiss', 52)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (38, N'Heart of the Night', 53)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (39, N'International Superhits', 54)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (40, N'Into The Light', 55)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (41, N'Meus Momentos', 56)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (42, N'Minha História', 57)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (43, N'MK III The Final Concerts [Disc 1]', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (44, N'Physical Graffiti [Disc 1]', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (45, N'Sambas De Enredo 2001', 21)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (46, N'Supernatural', 59)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (47, N'The Best of Ed Motta', 37)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (48, N'The Essential Miles Davis [Disc 1]', 68)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (49, N'The Essential Miles Davis [Disc 2]', 68)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (50, N'The Final Concerts (Disc 2)', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (51, N'Up An'' Atom', 69)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (52, N'Vinícius De Moraes - Sem Limite', 70)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (53, N'Vozes do MPB', 21)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (54, N'Chronicle, Vol. 1', 76)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (55, N'Chronicle, Vol. 2', 76)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (56, N'Cássia Eller - Coleção Sem Limite [Disc 2]', 77)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (57, N'Cássia Eller - Sem Limite [Disc 1]', 77)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (58, N'Come Taste The Band', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (59, N'Deep Purple In Rock', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (60, N'Fireball', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (61, N'Knocking at Your Back Door: The Best Of Deep Purple in the 80''s', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (62, N'Machine Head', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (63, N'Purpendicular', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (64, N'Slaves And Masters', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (65, N'Stormbringer', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (66, N'The Battle Rages On', 58)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (67, N'Vault: Def Leppard''s Greatest Hits', 78)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (68, N'Outbreak', 79)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (69, N'Djavan Ao Vivo - Vol. 02', 80)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (70, N'Djavan Ao Vivo - Vol. 1', 80)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (71, N'Elis Regina-Minha História', 41)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (72, N'The Cream Of Clapton', 81)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (73, N'Unplugged', 81)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (74, N'Album Of The Year', 82)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (75, N'Angel Dust', 82)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (76, N'King For A Day Fool For A Lifetime', 82)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (77, N'The Real Thing', 82)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (78, N'Deixa Entrar', 83)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (79, N'In Your Honor [Disc 1]', 84)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (80, N'In Your Honor [Disc 2]', 84)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (81, N'One By One', 84)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (82, N'The Colour And The Shape', 84)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (83, N'My Way: The Best Of Frank Sinatra [Disc 1]', 85)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (84, N'Roda De Funk', 86)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (85, N'As Canções de Eu Tu Eles', 27)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (86, N'Quanta Gente Veio Ver (Live)', 27)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (87, N'Quanta Gente Veio ver--Bônus De Carnaval', 27)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (88, N'Faceless', 87)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (89, N'American Idiot', 54)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (90, N'Appetite for Destruction', 88)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (91, N'Use Your Illusion I', 88)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (92, N'Use Your Illusion II', 88)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (93, N'Blue Moods', 89)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (94, N'A Matter of Life and Death', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (95, N'A Real Dead One', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (96, N'A Real Live One', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (97, N'Brave New World', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (98, N'Dance Of Death', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (99, N'Fear Of The Dark', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (100, N'Iron Maiden', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (101, N'Killers', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (102, N'Live After Death', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (103, N'Live At Donington 1992 (Disc 1)', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (104, N'Live At Donington 1992 (Disc 2)', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (105, N'No Prayer For The Dying', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (106, N'Piece Of Mind', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (107, N'Powerslave', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (108, N'Rock In Rio [CD1]', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (109, N'Rock In Rio [CD2]', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (110, N'Seventh Son of a Seventh Son', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (111, N'Somewhere in Time', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (112, N'The Number of The Beast', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (113, N'The X Factor', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (114, N'Virtual XI', 90)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (115, N'Sex Machine', 91)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (116, N'Emergency On Planet Earth', 92)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (117, N'Synkronized', 92)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (118, N'The Return Of The Space Cowboy', 92)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (119, N'Get Born', 93)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (120, N'Are You Experienced?', 94)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (121, N'Surfing with the Alien (Remastered)', 95)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (122, N'Jorge Ben Jor 25 Anos', 46)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (123, N'Jota Quest-1995', 96)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (124, N'Cafezinho', 97)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (125, N'Living After Midnight', 98)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (126, N'Unplugged [Live]', 52)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (127, N'BBC Sessions [Disc 2] [Live]', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (128, N'Coda', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (129, N'Houses Of The Holy', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (130, N'In Through The Out Door', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (131, N'IV', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (132, N'Led Zeppelin I', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (133, N'Led Zeppelin II', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (134, N'Led Zeppelin III', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (135, N'Physical Graffiti [Disc 2]', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (136, N'Presence', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (137, N'The Song Remains The Same (Disc 1)', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (138, N'The Song Remains The Same (Disc 2)', 22)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (139, N'A TempestadeTempestade Ou O Livro Dos Dias', 99)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (140, N'Mais Do Mesmo', 99)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (141, N'Greatest Hits', 100)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (142, N'Lulu Santos - RCA 100 Anos De Música - Álbum 01', 101)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (143, N'Lulu Santos - RCA 100 Anos De Música - Álbum 02', 101)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (144, N'Misplaced Childhood', 102)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (145, N'Barulhinho Bom', 103)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (146, N'Seek And Shall Find: More Of The Best (1963-1981)', 104)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (147, N'The Best Of Men At Work', 105)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (148, N'Black Album', 50)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (149, N'Garage Inc. (Disc 2)', 50)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (150, N'Kill ''Em All', 50)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (151, N'Load', 50)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (152, N'Master Of Puppets', 50)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (153, N'ReLoad', 50)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (154, N'Ride The Lightning', 50)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (155, N'St. Anger', 50)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (156, N'...And Justice For All', 50)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (157, N'Miles Ahead', 68)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (158, N'Milton Nascimento Ao Vivo', 42)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (159, N'Minas', 42)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (160, N'Ace Of Spades', 106)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (161, N'Demorou...', 108)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (162, N'Motley Crue Greatest Hits', 109)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (163, N'From The Muddy Banks Of The Wishkah [Live]', 110)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (164, N'Nevermind', 110)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (165, N'Compositores', 111)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (166, N'Olodum', 112)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (167, N'Acústico MTV', 113)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (168, N'Arquivo II', 113)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (169, N'Arquivo Os Paralamas Do Sucesso', 113)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (170, N'Bark at the Moon (Remastered)', 114)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (171, N'Blizzard of Ozz', 114)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (172, N'Diary of a Madman (Remastered)', 114)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (173, N'No More Tears (Remastered)', 114)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (174, N'Tribute', 114)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (175, N'Walking Into Clarksdale', 115)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (176, N'Original Soundtracks 1', 116)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (177, N'The Beast Live', 117)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (178, N'Live On Two Legs [Live]', 118)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (179, N'Pearl Jam', 118)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (180, N'Riot Act', 118)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (181, N'Ten', 118)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (182, N'Vs.', 118)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (183, N'Dark Side Of The Moon', 120)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (184, N'Os Cães Ladram Mas A Caravana Não Pára', 121)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (185, N'Greatest Hits I', 51)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (186, N'News Of The World', 51)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (187, N'Out Of Time', 122)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (188, N'Green', 124)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (189, N'New Adventures In Hi-Fi', 124)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (190, N'The Best Of R.E.M.: The IRS Years', 124)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (191, N'Cesta Básica', 125)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (192, N'Raul Seixas', 126)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (193, N'Blood Sugar Sex Magik', 127)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (194, N'By The Way', 127)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (195, N'Californication', 127)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (196, N'Retrospective I (1974-1980)', 128)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (197, N'Santana - As Years Go By', 59)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (198, N'Santana Live', 59)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (199, N'Maquinarama', 130)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (200, N'O Samba Poconé', 130)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (201, N'Judas 0: B-Sides and Rarities', 131)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (202, N'Rotten Apples: Greatest Hits', 131)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (203, N'A-Sides', 132)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (204, N'Morning Dance', 53)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (205, N'In Step', 133)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (206, N'Core', 134)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (207, N'Mezmerize', 135)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (208, N'[1997] Black Light Syndrome', 136)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (209, N'Live [Disc 1]', 137)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (210, N'Live [Disc 2]', 137)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (211, N'The Singles', 138)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (212, N'Beyond Good And Evil', 139)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (213, N'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]', 139)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (214, N'The Doors', 140)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (215, N'The Police Greatest Hits', 141)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (216, N'Hot Rocks, 1964-1971 (Disc 1)', 142)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (217, N'No Security', 142)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (218, N'Voodoo Lounge', 142)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (219, N'Tangents', 143)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (220, N'Transmission', 143)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (221, N'My Generation - The Very Best Of The Who', 144)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (222, N'Serie Sem Limite (Disc 1)', 145)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (223, N'Serie Sem Limite (Disc 2)', 145)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (224, N'Acústico', 146)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (225, N'Volume Dois', 146)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (226, N'Battlestar Galactica: The Story So Far', 147)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (227, N'Battlestar Galactica, Season 3', 147)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (228, N'Heroes, Season 1', 148)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (229, N'Lost, Season 3', 149)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (230, N'Lost, Season 1', 149)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (231, N'Lost, Season 2', 149)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (232, N'Achtung Baby', 150)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (233, N'All That You Can''t Leave Behind', 150)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (234, N'B-Sides 1980-1990', 150)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (235, N'How To Dismantle An Atomic Bomb', 150)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (236, N'Pop', 150)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (237, N'Rattle And Hum', 150)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (238, N'The Best Of 1980-1990', 150)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (239, N'War', 150)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (240, N'Zooropa', 150)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (241, N'UB40 The Best Of - Volume Two [UK]', 151)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (242, N'Diver Down', 152)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (243, N'The Best Of Van Halen, Vol. I', 152)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (244, N'Van Halen', 152)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (245, N'Van Halen III', 152)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (246, N'Contraband', 153)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (247, N'Vinicius De Moraes', 72)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (248, N'Ao Vivo [IMPORT]', 155)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (249, N'The Office, Season 1', 156)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (250, N'The Office, Season 2', 156)
INSERT INTO [dbo].[Album] ([AlbumId], [Title], [ArtistId]) VALUES (251, N'The Office, Season 3', 156)

